### PR TITLE
Fix `ManualExpect` for cases with destructured error

### LINKED ISSUE #365: `manual_expect` fixer returns not compilable code.
### Problem

https://github.com/software-mansion/cairo-lint/blob/58a224c3afb39a363b36ec176b65e4043af6a3cb/tests/manual/manual_expect.rs#L434. This test generates code that doesn't compile.

### Steps

_No response_

### Scarb Version

```text
2.11.4
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Arcticae**
Closes #365

### CODE REVIEW

File: src/lints/manual/mod.rs [hunk 1]
```diff
@@ -252,10 +252,18 @@ fn check_syntax_err_arm(
...
+                if func_name != PANIC_WITH_FELT252 {
+                    return false;
+                }
+
+                let Some(error_pattern_variable) = extract_pattern_variable(pattern, arenas) else {
+                    return true;
+                };
+
+                // A simplistic approach to detecting if user intends to use the destructured error
+                return error_pattern_variable.name.starts_with("_");
```
[the remark this answers is not in the document]
Comment (Draggu) [reply src/lints/manual/mod.rs:264]: Can't we just check if compiler diagnostic for `unused variable` was generated?

**Review by wawel37 — APPROVED** [review]

File: src/lints/manual/helpers.rs [hunk 2]
```diff
@@ -435,3 +449,43 @@ pub fn extract_tail_or_preserve_expr<'a>(expr: &'a Expr, arenas: &'a Arenas) ->
...
+        return false;
+    };
+    diags.get_all().iter().any(|diagnostic| {
+        diagnostic.stable_location.stable_ptr() == variable_syntax_stable_ptr
+            && diagnostic.kind == SemanticDiagnosticKind::UnusedVariable
+    })
+}
+
+// TODO: Re-write this to use `get_semantic_diagnostics` once linting is performed from within a query group
+/// Gets the semantic diagnostics in functions bodies scopes
```
Comment (Draggu) [inline src/lints/manual/helpers.rs:470]: It is stripped version of `get_semantic_diagnostics`, it is designed to correctly find only `SemanticDiagnosticKind::UnusedVariable`. Please note that here

File: tests/manual/manual_expect.rs [hunk 3]
```diff
@@ -436,28 +460,50 @@ fn test_manual_match_result_fixer() {
...
     |     };
     |_____^
+    Unused variable. Consider ignoring by prefixing with `_`.
+     --> lib.cairo:8:21
+            Result::Err(err) => core::panic_with_felt252(panic_value)
+                        ^^^
     ");
 }
 
-// TODO: https://github.com/software-mansion/cairo-lint/issues/365.
```
Comment (Draggu) [inline tests/manual/manual_expect.rs:450]: Use `#[ignore]` instead of commenting

Comment (Draggu) [reply tests/manual/manual_expect.rs:450]: My bad, im blind

**Review by Draggu — APPROVED** [review]

**Review by wawel37 — APPROVED** [review]
