### PR TITLE
Format fixed files in public API

### LINKED ISSUE #340: Add cairo formatter to `apply_file_fixes` as it's done in tests
### Problem

We want to format applied fixes using cairo formatter from `cairo-lang`formatter`. We are already doing that in tests (yet to be merged, but still) here https://github.com/software-mansion/cairo-lint/blob/21dfc33f7c2a680178e6f8eaf5974b32f568308e/tests/helpers/mod.rs#L93

### Proposed Solution

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by wawel37**
Resolves #340 
Tested with scarb locally. It formats the fixed file (as well as removes duplicated imports)

### CODE REVIEW

File: src/fixes.rs [hunk 1]
```diff
@@ -91,8 +91,8 @@ pub fn get_fixes_without_resolving_overlapping(
             if let Some(import_paths) = import_addition_paths {
                 let imports_suggestion = import_paths
                     .iter()
-                    .map(|import_path| format!("use {};", import_path))
-                    .join("\n");
+                    .map(|import_path| format!("use {};\n", import_path))
```
Comment (Arcticae) [inline src/fixes.rs:94]: why not `filter_map` here? the problem was empty strings being joined by `\n` - right?

**Review by Arcticae — COMMENTED** [review]
I have 2 questions about this:
1. How is the config obtained - from scarb's config/CLI whatever else? It's up to the APIs user - right?
2. Should we always format the file?

File: src/fixes.rs (hunk 1 above)
Comment (wawel37) [reply src/fixes.rs:94]: No, the problem was that with single import, it wasn't adding the `\n`

**Comment by wawel37** [comment]
> I have 2 questions about this:
> 
> 1. How is the config obtained - from scarb's config/CLI whatever else? It's up to the APIs user - right?
> 2. Should we always format the file?

1. That's true. In scarb it's the same as it's done here https://github.com/software-mansion/scarb/blob/753b3d31c39011246eb2e1d8d038cb98aa2317dd/scarb/src/ops/fmt.rs#L81.
2. Most of the lints benefit a lot from that as they do not format the fixed code to the very last detail. This way we will always have consistent fixer results. It also formats only the file that contained any fixes. 

Also, the formatting is necessary to some obscure fixer cases, as cairo-formatter removes duplicated imports itself.

**Review by Arcticae — APPROVED** [review]
