### PR TITLE
Do not trigger  `manual_unwrap_or` for non-droppable values

### LINKED ISSUE #387: `manual_unwrap_or` should not fire if there is no `+Drop<T>`
### Problem

```cairo
pub fn invoke<T, +Destruct<T>, +Drop<T>, +Serde<T>, R, +Serde<R>>(
    connection_string: ByteArray, selector: felt252, calldata: T,
) -> Result<R> {
    let mut input: Array<felt252> = array![];
    connection_string.serialize(ref input);
    selector.serialize(ref input);
    calldata.serialize(ref input);

    let mut output = cheatcode::<'oracle_invoke'>(input.span());

    match Serde::<Result<R>>::deserialize(ref output) {
        Option::Some(result) => result,
        Option::None => Err(deserialization_error()),
    }
}
```

yields

```
warn: Plugin diagnostic: Manual `unwrap_or` detected. Consider using `unwrap_or()` instead.
 --> /Users/mk/Developer/software-mansion/cairo-oracle/src/lib.cairo:146:5-149:5
      match Serde::<Result<R>>::deserialize(ref output) {
 _____^
| ...
|     }
|_____^
```

but I cannot do 

```cairo
pub fn invoke<T, +Destruct<T>, +Drop<T>, +Serde<T>, R, +Serde<R>>(
    connection_string: ByteArray, selector: felt252, calldata: T,
) -> Result<R> {
    let mut input: Array<felt252> = array![];
    connection_string.serialize(ref input);
    selector.serialize(ref input);
    calldata.serialize(ref input);

    let mut output = cheatcode::<'oracle_invoke'>(input.span());

    Serde::<Result<R>>::deserialize(ref output).unwrap_or_else(|| Err(deserialization_error()))
}
```

because 

```
error: Trait has no implementation in context: core::traits::Drop::<core::result::Result::<R, oracle::Error>>.
 --> /Users/mk/Developer/software-mansion/cairo-oracle/src/lib.cairo:145:49
    Serde::<Result<R>>::deserialize(ref output).unwrap_or_else(|| Err(deserialization_error()))
```

### Steps

_No response_

### Scarb Version

```text
2.11.4
```

### Possible Solution(s)

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by integraledelebesgue**
Closes #387

### CODE REVIEW

File: tests/manual/manual_unwrap_or.rs [hunk 1]
```diff
@@ -1145,3 +1211,39 @@ fn allow_match_with_tuple_option_diagnostics() {
...
+    test_lint_diagnostics!(MATCH_WITH_DERIVE_DROP_TYPE, @r"
+    Plugin diagnostic: Manual `unwrap_or` detected. Consider using `unwrap_or()` instead.
+     --> lib.cairo:10:5-13:5
+          match a {
+     _____^
+    | ...
+    |     };
+    |_____^
+    ");
+}
```
Comment (wawel37) [inline tests/manual/manual_unwrap_or.rs:1249]: Please include fixer tests for those 2, as the `manual_unwrap_or` has a fixer itself.
